// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"
)

// WarningsMock is a mock implementation of events.Warnings.
//
//	func TestSomethingThatUsesWarnings(t *testing.T) {
//
//		// make and configure a mocked events.Warnings
//		mockedWarnings := &WarningsMock{
//			AddFunc: func(ctx context.Context, userID int64, userName string) error {
//				panic("mock out the Add method")
//			},
//			CountWithinFunc: func(ctx context.Context, userID int64, window time.Duration) (int, error) {
//				panic("mock out the CountWithin method")
//			},
//		}
//
//		// use mockedWarnings in code that requires events.Warnings
//		// and then make assertions.
//
//	}
type WarningsMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, userID int64, userName string) error

	// CountWithinFunc mocks the CountWithin method.
	CountWithinFunc func(ctx context.Context, userID int64, window time.Duration) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// UserName is the userName argument value.
			UserName string
		}
		// CountWithin holds details about calls to the CountWithin method.
		CountWithin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// Window is the window argument value.
			Window time.Duration
		}
	}
	lockAdd         sync.RWMutex
	lockCountWithin sync.RWMutex
}

// Add calls AddFunc.
func (mock *WarningsMock) Add(ctx context.Context, userID int64, userName string) error {
	if mock.AddFunc == nil {
		panic("WarningsMock.AddFunc: method is nil but Warnings.Add was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		UserID   int64
		UserName string
	}{
		Ctx:      ctx,
		UserID:   userID,
		UserName: userName,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, userID, userName)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedWarnings.AddCalls())
func (mock *WarningsMock) AddCalls() []struct {
	Ctx      context.Context
	UserID   int64
	UserName string
} {
	var calls []struct {
		Ctx      context.Context
		UserID   int64
		UserName string
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// ResetAddCalls reset all the calls that were made to Add.
func (mock *WarningsMock) ResetAddCalls() {
	mock.lockAdd.Lock()
	mock.calls.Add = nil
	mock.lockAdd.Unlock()
}

// CountWithin calls CountWithinFunc.
func (mock *WarningsMock) CountWithin(ctx context.Context, userID int64, window time.Duration) (int, error) {
	if mock.CountWithinFunc == nil {
		panic("WarningsMock.CountWithinFunc: method is nil but Warnings.CountWithin was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		Window time.Duration
	}{
		Ctx:    ctx,
		UserID: userID,
		Window: window,
	}
	mock.lockCountWithin.Lock()
	mock.calls.CountWithin = append(mock.calls.CountWithin, callInfo)
	mock.lockCountWithin.Unlock()
	return mock.CountWithinFunc(ctx, userID, window)
}

// CountWithinCalls gets all the calls that were made to CountWithin.
// Check the length with:
//
//	len(mockedWarnings.CountWithinCalls())
func (mock *WarningsMock) CountWithinCalls() []struct {
	Ctx    context.Context
	UserID int64
	Window time.Duration
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		Window time.Duration
	}
	mock.lockCountWithin.RLock()
	calls = mock.calls.CountWithin
	mock.lockCountWithin.RUnlock()
	return calls
}

// ResetCountWithinCalls reset all the calls that were made to CountWithin.
func (mock *WarningsMock) ResetCountWithinCalls() {
	mock.lockCountWithin.Lock()
	mock.calls.CountWithin = nil
	mock.lockCountWithin.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *WarningsMock) ResetCalls() {
	mock.lockAdd.Lock()
	mock.calls.Add = nil
	mock.lockAdd.Unlock()

	mock.lockCountWithin.Lock()
	mock.calls.CountWithin = nil
	mock.lockCountWithin.Unlock()
}
