// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"google.golang.org/genai"
	"sync"
)

// GeminiClientMock is a mock implementation of tgspam.geminiClient.
//
//	func TestSomethingThatUsesgeminiClient(t *testing.T) {
//
//		// make and configure a mocked tgspam.geminiClient
//		mockedgeminiClient := &GeminiClientMock{
//			GenerateContentFunc: func(contextMoqParam context.Context, s string, contents []*genai.Content, generateContentConfig *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error) {
//				panic("mock out the GenerateContent method")
//			},
//		}
//
//		// use mockedgeminiClient in code that requires tgspam.geminiClient
//		// and then make assertions.
//
//	}
type GeminiClientMock struct {
	// GenerateContentFunc mocks the GenerateContent method.
	GenerateContentFunc func(contextMoqParam context.Context, s string, contents []*genai.Content, generateContentConfig *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateContent holds details about calls to the GenerateContent method.
		GenerateContent []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// Contents is the contents argument value.
			Contents []*genai.Content
			// GenerateContentConfig is the generateContentConfig argument value.
			GenerateContentConfig *genai.GenerateContentConfig
		}
	}
	lockGenerateContent sync.RWMutex
}

// GenerateContent calls GenerateContentFunc.
func (mock *GeminiClientMock) GenerateContent(contextMoqParam context.Context, s string, contents []*genai.Content, generateContentConfig *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error) {
	if mock.GenerateContentFunc == nil {
		panic("GeminiClientMock.GenerateContentFunc: method is nil but geminiClient.GenerateContent was just called")
	}
	callInfo := struct {
		ContextMoqParam       context.Context
		S                     string
		Contents              []*genai.Content
		GenerateContentConfig *genai.GenerateContentConfig
	}{
		ContextMoqParam:       contextMoqParam,
		S:                     s,
		Contents:              contents,
		GenerateContentConfig: generateContentConfig,
	}
	mock.lockGenerateContent.Lock()
	mock.calls.GenerateContent = append(mock.calls.GenerateContent, callInfo)
	mock.lockGenerateContent.Unlock()
	return mock.GenerateContentFunc(contextMoqParam, s, contents, generateContentConfig)
}

// GenerateContentCalls gets all the calls that were made to GenerateContent.
// Check the length with:
//
//	len(mockedgeminiClient.GenerateContentCalls())
func (mock *GeminiClientMock) GenerateContentCalls() []struct {
	ContextMoqParam       context.Context
	S                     string
	Contents              []*genai.Content
	GenerateContentConfig *genai.GenerateContentConfig
} {
	var calls []struct {
		ContextMoqParam       context.Context
		S                     string
		Contents              []*genai.Content
		GenerateContentConfig *genai.GenerateContentConfig
	}
	mock.lockGenerateContent.RLock()
	calls = mock.calls.GenerateContent
	mock.lockGenerateContent.RUnlock()
	return calls
}

// ResetGenerateContentCalls reset all the calls that were made to GenerateContent.
func (mock *GeminiClientMock) ResetGenerateContentCalls() {
	mock.lockGenerateContent.Lock()
	mock.calls.GenerateContent = nil
	mock.lockGenerateContent.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *GeminiClientMock) ResetCalls() {
	mock.lockGenerateContent.Lock()
	mock.calls.GenerateContent = nil
	mock.lockGenerateContent.Unlock()
}
