// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// MessageCounterMock is a mock implementation of tgspam.MessageCounter.
//
//	func TestSomethingThatUsesMessageCounter(t *testing.T) {
//
//		// make and configure a mocked tgspam.MessageCounter
//		mockedMessageCounter := &MessageCounterMock{
//			CountUserMessagesFunc: func(ctx context.Context, userID string) (int, error) {
//				panic("mock out the CountUserMessages method")
//			},
//			UserMessageIDsFunc: func(ctx context.Context, userID string, limit int) ([]int, error) {
//				panic("mock out the UserMessageIDs method")
//			},
//		}
//
//		// use mockedMessageCounter in code that requires tgspam.MessageCounter
//		// and then make assertions.
//
//	}
type MessageCounterMock struct {
	// CountUserMessagesFunc mocks the CountUserMessages method.
	CountUserMessagesFunc func(ctx context.Context, userID string) (int, error)

	// UserMessageIDsFunc mocks the UserMessageIDs method.
	UserMessageIDsFunc func(ctx context.Context, userID string, limit int) ([]int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountUserMessages holds details about calls to the CountUserMessages method.
		CountUserMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// UserMessageIDs holds details about calls to the UserMessageIDs method.
		UserMessageIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCountUserMessages sync.RWMutex
	lockUserMessageIDs    sync.RWMutex
}

// CountUserMessages calls CountUserMessagesFunc.
func (mock *MessageCounterMock) CountUserMessages(ctx context.Context, userID string) (int, error) {
	if mock.CountUserMessagesFunc == nil {
		panic("MessageCounterMock.CountUserMessagesFunc: method is nil but MessageCounter.CountUserMessages was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockCountUserMessages.Lock()
	mock.calls.CountUserMessages = append(mock.calls.CountUserMessages, callInfo)
	mock.lockCountUserMessages.Unlock()
	return mock.CountUserMessagesFunc(ctx, userID)
}

// CountUserMessagesCalls gets all the calls that were made to CountUserMessages.
// Check the length with:
//
//	len(mockedMessageCounter.CountUserMessagesCalls())
func (mock *MessageCounterMock) CountUserMessagesCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockCountUserMessages.RLock()
	calls = mock.calls.CountUserMessages
	mock.lockCountUserMessages.RUnlock()
	return calls
}

// ResetCountUserMessagesCalls reset all the calls that were made to CountUserMessages.
func (mock *MessageCounterMock) ResetCountUserMessagesCalls() {
	mock.lockCountUserMessages.Lock()
	mock.calls.CountUserMessages = nil
	mock.lockCountUserMessages.Unlock()
}

// UserMessageIDs calls UserMessageIDsFunc.
func (mock *MessageCounterMock) UserMessageIDs(ctx context.Context, userID string, limit int) ([]int, error) {
	if mock.UserMessageIDsFunc == nil {
		panic("MessageCounterMock.UserMessageIDsFunc: method is nil but MessageCounter.UserMessageIDs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
		Limit  int
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
	}
	mock.lockUserMessageIDs.Lock()
	mock.calls.UserMessageIDs = append(mock.calls.UserMessageIDs, callInfo)
	mock.lockUserMessageIDs.Unlock()
	return mock.UserMessageIDsFunc(ctx, userID, limit)
}

// UserMessageIDsCalls gets all the calls that were made to UserMessageIDs.
// Check the length with:
//
//	len(mockedMessageCounter.UserMessageIDsCalls())
func (mock *MessageCounterMock) UserMessageIDsCalls() []struct {
	Ctx    context.Context
	UserID string
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
		Limit  int
	}
	mock.lockUserMessageIDs.RLock()
	calls = mock.calls.UserMessageIDs
	mock.lockUserMessageIDs.RUnlock()
	return calls
}

// ResetUserMessageIDsCalls reset all the calls that were made to UserMessageIDs.
func (mock *MessageCounterMock) ResetUserMessageIDsCalls() {
	mock.lockUserMessageIDs.Lock()
	mock.calls.UserMessageIDs = nil
	mock.lockUserMessageIDs.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MessageCounterMock) ResetCalls() {
	mock.lockCountUserMessages.Lock()
	mock.calls.CountUserMessages = nil
	mock.lockCountUserMessages.Unlock()

	mock.lockUserMessageIDs.Lock()
	mock.calls.UserMessageIDs = nil
	mock.lockUserMessageIDs.Unlock()
}
