// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// ApprovedUsersStoreMock is a mock implementation of bot.ApprovedUsersStore.
//
//	func TestSomethingThatUsesApprovedUsersStore(t *testing.T) {
//
//		// make and configure a mocked bot.ApprovedUsersStore
//		mockedApprovedUsersStore := &ApprovedUsersStoreMock{
//			DeleteFunc: func(id string) error {
//				panic("mock out the Delete method")
//			},
//		}
//
//		// use mockedApprovedUsersStore in code that requires bot.ApprovedUsersStore
//		// and then make assertions.
//
//	}
type ApprovedUsersStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID string
		}
	}
	lockDelete sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *ApprovedUsersStoreMock) Delete(id string) error {
	if mock.DeleteFunc == nil {
		panic("ApprovedUsersStoreMock.DeleteFunc: method is nil but ApprovedUsersStore.Delete was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedApprovedUsersStore.DeleteCalls())
func (mock *ApprovedUsersStoreMock) DeleteCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ResetDeleteCalls reset all the calls that were made to Delete.
func (mock *ApprovedUsersStoreMock) ResetDeleteCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ApprovedUsersStoreMock) ResetCalls() {
	mock.lockDelete.Lock()
	mock.calls.Delete = nil
	mock.lockDelete.Unlock()
}
