// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/umputun/tg-spam/lib"
	"sync"
)

// DetectorMock is a mock implementation of webapi.SpamFilter.
//
//	func TestSomethingThatUsesDetector(t *testing.T) {
//
//		// make and configure a mocked webapi.SpamFilter
//		mockedDetector := &DetectorMock{
//			AddApprovedUsersFunc: func(ids ...string)  {
//				panic("mock out the AddApprovedUsers method")
//			},
//			ApprovedUsersFunc: func() []string {
//				panic("mock out the ApprovedUsers method")
//			},
//			CheckFunc: func(msg string, userID string) (bool, []lib.CheckResult) {
//				panic("mock out the Check method")
//			},
//			RemoveApprovedUsersFunc: func(ids ...string)  {
//				panic("mock out the RemoveApprovedUsers method")
//			},
//			UpdateHamFunc: func(msg string) error {
//				panic("mock out the UpdateHam method")
//			},
//			UpdateSpamFunc: func(msg string) error {
//				panic("mock out the UpdateSpam method")
//			},
//		}
//
//		// use mockedDetector in code that requires webapi.SpamFilter
//		// and then make assertions.
//
//	}
type DetectorMock struct {
	// AddApprovedUsersFunc mocks the AddApprovedUsers method.
	AddApprovedUsersFunc func(ids ...string)

	// ApprovedUsersFunc mocks the ApprovedUsers method.
	ApprovedUsersFunc func() []string

	// CheckFunc mocks the Check method.
	CheckFunc func(msg string, userID string) (bool, []lib.CheckResult)

	// RemoveApprovedUsersFunc mocks the RemoveApprovedUsers method.
	RemoveApprovedUsersFunc func(ids ...string)

	// UpdateHamFunc mocks the UpdateHam method.
	UpdateHamFunc func(msg string) error

	// UpdateSpamFunc mocks the UpdateSpam method.
	UpdateSpamFunc func(msg string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddApprovedUsers holds details about calls to the AddApprovedUsers method.
		AddApprovedUsers []struct {
			// Ids is the ids argument value.
			Ids []string
		}
		// ApprovedUsers holds details about calls to the ApprovedUsers method.
		ApprovedUsers []struct {
		}
		// Check holds details about calls to the Check method.
		Check []struct {
			// Msg is the msg argument value.
			Msg string
			// UserID is the userID argument value.
			UserID string
		}
		// RemoveApprovedUsers holds details about calls to the RemoveApprovedUsers method.
		RemoveApprovedUsers []struct {
			// Ids is the ids argument value.
			Ids []string
		}
		// UpdateHam holds details about calls to the UpdateHam method.
		UpdateHam []struct {
			// Msg is the msg argument value.
			Msg string
		}
		// UpdateSpam holds details about calls to the UpdateSpam method.
		UpdateSpam []struct {
			// Msg is the msg argument value.
			Msg string
		}
	}
	lockAddApprovedUsers    sync.RWMutex
	lockApprovedUsers       sync.RWMutex
	lockCheck               sync.RWMutex
	lockRemoveApprovedUsers sync.RWMutex
	lockUpdateHam           sync.RWMutex
	lockUpdateSpam          sync.RWMutex
}

// AddApprovedUsers calls AddApprovedUsersFunc.
func (mock *DetectorMock) AddApprovedUsers(ids ...string) {
	if mock.AddApprovedUsersFunc == nil {
		panic("DetectorMock.AddApprovedUsersFunc: method is nil but SpamFilter.AddApprovedUsers was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockAddApprovedUsers.Lock()
	mock.calls.AddApprovedUsers = append(mock.calls.AddApprovedUsers, callInfo)
	mock.lockAddApprovedUsers.Unlock()
	mock.AddApprovedUsersFunc(ids...)
}

// AddApprovedUsersCalls gets all the calls that were made to AddApprovedUsers.
// Check the length with:
//
//	len(mockedDetector.AddApprovedUsersCalls())
func (mock *DetectorMock) AddApprovedUsersCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockAddApprovedUsers.RLock()
	calls = mock.calls.AddApprovedUsers
	mock.lockAddApprovedUsers.RUnlock()
	return calls
}

// ResetAddApprovedUsersCalls reset all the calls that were made to AddApprovedUsers.
func (mock *DetectorMock) ResetAddApprovedUsersCalls() {
	mock.lockAddApprovedUsers.Lock()
	mock.calls.AddApprovedUsers = nil
	mock.lockAddApprovedUsers.Unlock()
}

// ApprovedUsers calls ApprovedUsersFunc.
func (mock *DetectorMock) ApprovedUsers() []string {
	if mock.ApprovedUsersFunc == nil {
		panic("DetectorMock.ApprovedUsersFunc: method is nil but SpamFilter.ApprovedUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = append(mock.calls.ApprovedUsers, callInfo)
	mock.lockApprovedUsers.Unlock()
	return mock.ApprovedUsersFunc()
}

// ApprovedUsersCalls gets all the calls that were made to ApprovedUsers.
// Check the length with:
//
//	len(mockedDetector.ApprovedUsersCalls())
func (mock *DetectorMock) ApprovedUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockApprovedUsers.RLock()
	calls = mock.calls.ApprovedUsers
	mock.lockApprovedUsers.RUnlock()
	return calls
}

// ResetApprovedUsersCalls reset all the calls that were made to ApprovedUsers.
func (mock *DetectorMock) ResetApprovedUsersCalls() {
	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = nil
	mock.lockApprovedUsers.Unlock()
}

// Check calls CheckFunc.
func (mock *DetectorMock) Check(msg string, userID string) (bool, []lib.CheckResult) {
	if mock.CheckFunc == nil {
		panic("DetectorMock.CheckFunc: method is nil but SpamFilter.Check was just called")
	}
	callInfo := struct {
		Msg    string
		UserID string
	}{
		Msg:    msg,
		UserID: userID,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(msg, userID)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedDetector.CheckCalls())
func (mock *DetectorMock) CheckCalls() []struct {
	Msg    string
	UserID string
} {
	var calls []struct {
		Msg    string
		UserID string
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}

// ResetCheckCalls reset all the calls that were made to Check.
func (mock *DetectorMock) ResetCheckCalls() {
	mock.lockCheck.Lock()
	mock.calls.Check = nil
	mock.lockCheck.Unlock()
}

// RemoveApprovedUsers calls RemoveApprovedUsersFunc.
func (mock *DetectorMock) RemoveApprovedUsers(ids ...string) {
	if mock.RemoveApprovedUsersFunc == nil {
		panic("DetectorMock.RemoveApprovedUsersFunc: method is nil but SpamFilter.RemoveApprovedUsers was just called")
	}
	callInfo := struct {
		Ids []string
	}{
		Ids: ids,
	}
	mock.lockRemoveApprovedUsers.Lock()
	mock.calls.RemoveApprovedUsers = append(mock.calls.RemoveApprovedUsers, callInfo)
	mock.lockRemoveApprovedUsers.Unlock()
	mock.RemoveApprovedUsersFunc(ids...)
}

// RemoveApprovedUsersCalls gets all the calls that were made to RemoveApprovedUsers.
// Check the length with:
//
//	len(mockedDetector.RemoveApprovedUsersCalls())
func (mock *DetectorMock) RemoveApprovedUsersCalls() []struct {
	Ids []string
} {
	var calls []struct {
		Ids []string
	}
	mock.lockRemoveApprovedUsers.RLock()
	calls = mock.calls.RemoveApprovedUsers
	mock.lockRemoveApprovedUsers.RUnlock()
	return calls
}

// ResetRemoveApprovedUsersCalls reset all the calls that were made to RemoveApprovedUsers.
func (mock *DetectorMock) ResetRemoveApprovedUsersCalls() {
	mock.lockRemoveApprovedUsers.Lock()
	mock.calls.RemoveApprovedUsers = nil
	mock.lockRemoveApprovedUsers.Unlock()
}

// UpdateHam calls UpdateHamFunc.
func (mock *DetectorMock) UpdateHam(msg string) error {
	if mock.UpdateHamFunc == nil {
		panic("DetectorMock.UpdateHamFunc: method is nil but SpamFilter.UpdateHam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = append(mock.calls.UpdateHam, callInfo)
	mock.lockUpdateHam.Unlock()
	return mock.UpdateHamFunc(msg)
}

// UpdateHamCalls gets all the calls that were made to UpdateHam.
// Check the length with:
//
//	len(mockedDetector.UpdateHamCalls())
func (mock *DetectorMock) UpdateHamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockUpdateHam.RLock()
	calls = mock.calls.UpdateHam
	mock.lockUpdateHam.RUnlock()
	return calls
}

// ResetUpdateHamCalls reset all the calls that were made to UpdateHam.
func (mock *DetectorMock) ResetUpdateHamCalls() {
	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()
}

// UpdateSpam calls UpdateSpamFunc.
func (mock *DetectorMock) UpdateSpam(msg string) error {
	if mock.UpdateSpamFunc == nil {
		panic("DetectorMock.UpdateSpamFunc: method is nil but SpamFilter.UpdateSpam was just called")
	}
	callInfo := struct {
		Msg string
	}{
		Msg: msg,
	}
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = append(mock.calls.UpdateSpam, callInfo)
	mock.lockUpdateSpam.Unlock()
	return mock.UpdateSpamFunc(msg)
}

// UpdateSpamCalls gets all the calls that were made to UpdateSpam.
// Check the length with:
//
//	len(mockedDetector.UpdateSpamCalls())
func (mock *DetectorMock) UpdateSpamCalls() []struct {
	Msg string
} {
	var calls []struct {
		Msg string
	}
	mock.lockUpdateSpam.RLock()
	calls = mock.calls.UpdateSpam
	mock.lockUpdateSpam.RUnlock()
	return calls
}

// ResetUpdateSpamCalls reset all the calls that were made to UpdateSpam.
func (mock *DetectorMock) ResetUpdateSpamCalls() {
	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DetectorMock) ResetCalls() {
	mock.lockAddApprovedUsers.Lock()
	mock.calls.AddApprovedUsers = nil
	mock.lockAddApprovedUsers.Unlock()

	mock.lockApprovedUsers.Lock()
	mock.calls.ApprovedUsers = nil
	mock.lockApprovedUsers.Unlock()

	mock.lockCheck.Lock()
	mock.calls.Check = nil
	mock.lockCheck.Unlock()

	mock.lockRemoveApprovedUsers.Lock()
	mock.calls.RemoveApprovedUsers = nil
	mock.lockRemoveApprovedUsers.Unlock()

	mock.lockUpdateHam.Lock()
	mock.calls.UpdateHam = nil
	mock.lockUpdateHam.Unlock()

	mock.lockUpdateSpam.Lock()
	mock.calls.UpdateSpam = nil
	mock.lockUpdateSpam.Unlock()
}
