// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/umputun/tg-spam/app/events"
	"sync"
)

// DMUsersProviderMock is a mock implementation of webapi.DMUsersProvider.
//
//	func TestSomethingThatUsesDMUsersProvider(t *testing.T) {
//
//		// make and configure a mocked webapi.DMUsersProvider
//		mockedDMUsersProvider := &DMUsersProviderMock{
//			GetDMUsersFunc: func() []events.DMUser {
//				panic("mock out the GetDMUsers method")
//			},
//		}
//
//		// use mockedDMUsersProvider in code that requires webapi.DMUsersProvider
//		// and then make assertions.
//
//	}
type DMUsersProviderMock struct {
	// GetDMUsersFunc mocks the GetDMUsers method.
	GetDMUsersFunc func() []events.DMUser

	// calls tracks calls to the methods.
	calls struct {
		// GetDMUsers holds details about calls to the GetDMUsers method.
		GetDMUsers []struct {
		}
	}
	lockGetDMUsers sync.RWMutex
}

// GetDMUsers calls GetDMUsersFunc.
func (mock *DMUsersProviderMock) GetDMUsers() []events.DMUser {
	if mock.GetDMUsersFunc == nil {
		panic("DMUsersProviderMock.GetDMUsersFunc: method is nil but DMUsersProvider.GetDMUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = append(mock.calls.GetDMUsers, callInfo)
	mock.lockGetDMUsers.Unlock()
	return mock.GetDMUsersFunc()
}

// GetDMUsersCalls gets all the calls that were made to GetDMUsers.
// Check the length with:
//
//	len(mockedDMUsersProvider.GetDMUsersCalls())
func (mock *DMUsersProviderMock) GetDMUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDMUsers.RLock()
	calls = mock.calls.GetDMUsers
	mock.lockGetDMUsers.RUnlock()
	return calls
}

// ResetGetDMUsersCalls reset all the calls that were made to GetDMUsers.
func (mock *DMUsersProviderMock) ResetGetDMUsersCalls() {
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = nil
	mock.lockGetDMUsers.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DMUsersProviderMock) ResetCalls() {
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = nil
	mock.lockGetDMUsers.Unlock()
}
