// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/umputun/tg-spam/app/events"
	"sync"
)

// DMUsersProviderMock is a mock implementation of webapi.DMUsersProvider.
//
//	func TestSomethingThatUsesDMUsersProvider(t *testing.T) {
//
//		// make and configure a mocked webapi.DMUsersProvider
//		mockedDMUsersProvider := &DMUsersProviderMock{
//			GetDMUsersFunc: func() []events.DMUser {
//				panic("mock out the GetDMUsers method")
//			},
//			SubscribeDMUsersFunc: func() <-chan events.DMUser {
//				panic("mock out the SubscribeDMUsers method")
//			},
//			UnsubscribeDMUsersFunc: func(dMUserCh <-chan events.DMUser)  {
//				panic("mock out the UnsubscribeDMUsers method")
//			},
//		}
//
//		// use mockedDMUsersProvider in code that requires webapi.DMUsersProvider
//		// and then make assertions.
//
//	}
type DMUsersProviderMock struct {
	// GetDMUsersFunc mocks the GetDMUsers method.
	GetDMUsersFunc func() []events.DMUser

	// SubscribeDMUsersFunc mocks the SubscribeDMUsers method.
	SubscribeDMUsersFunc func() <-chan events.DMUser

	// UnsubscribeDMUsersFunc mocks the UnsubscribeDMUsers method.
	UnsubscribeDMUsersFunc func(dMUserCh <-chan events.DMUser)

	// calls tracks calls to the methods.
	calls struct {
		// GetDMUsers holds details about calls to the GetDMUsers method.
		GetDMUsers []struct {
		}
		// SubscribeDMUsers holds details about calls to the SubscribeDMUsers method.
		SubscribeDMUsers []struct {
		}
		// UnsubscribeDMUsers holds details about calls to the UnsubscribeDMUsers method.
		UnsubscribeDMUsers []struct {
			// DMUserCh is the dMUserCh argument value.
			DMUserCh <-chan events.DMUser
		}
	}
	lockGetDMUsers         sync.RWMutex
	lockSubscribeDMUsers   sync.RWMutex
	lockUnsubscribeDMUsers sync.RWMutex
}

// GetDMUsers calls GetDMUsersFunc.
func (mock *DMUsersProviderMock) GetDMUsers() []events.DMUser {
	if mock.GetDMUsersFunc == nil {
		panic("DMUsersProviderMock.GetDMUsersFunc: method is nil but DMUsersProvider.GetDMUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = append(mock.calls.GetDMUsers, callInfo)
	mock.lockGetDMUsers.Unlock()
	return mock.GetDMUsersFunc()
}

// GetDMUsersCalls gets all the calls that were made to GetDMUsers.
// Check the length with:
//
//	len(mockedDMUsersProvider.GetDMUsersCalls())
func (mock *DMUsersProviderMock) GetDMUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDMUsers.RLock()
	calls = mock.calls.GetDMUsers
	mock.lockGetDMUsers.RUnlock()
	return calls
}

// ResetGetDMUsersCalls reset all the calls that were made to GetDMUsers.
func (mock *DMUsersProviderMock) ResetGetDMUsersCalls() {
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = nil
	mock.lockGetDMUsers.Unlock()
}

// SubscribeDMUsers calls SubscribeDMUsersFunc.
func (mock *DMUsersProviderMock) SubscribeDMUsers() <-chan events.DMUser {
	if mock.SubscribeDMUsersFunc == nil {
		panic("DMUsersProviderMock.SubscribeDMUsersFunc: method is nil but DMUsersProvider.SubscribeDMUsers was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSubscribeDMUsers.Lock()
	mock.calls.SubscribeDMUsers = append(mock.calls.SubscribeDMUsers, callInfo)
	mock.lockSubscribeDMUsers.Unlock()
	return mock.SubscribeDMUsersFunc()
}

// SubscribeDMUsersCalls gets all the calls that were made to SubscribeDMUsers.
// Check the length with:
//
//	len(mockedDMUsersProvider.SubscribeDMUsersCalls())
func (mock *DMUsersProviderMock) SubscribeDMUsersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSubscribeDMUsers.RLock()
	calls = mock.calls.SubscribeDMUsers
	mock.lockSubscribeDMUsers.RUnlock()
	return calls
}

// ResetSubscribeDMUsersCalls reset all the calls that were made to SubscribeDMUsers.
func (mock *DMUsersProviderMock) ResetSubscribeDMUsersCalls() {
	mock.lockSubscribeDMUsers.Lock()
	mock.calls.SubscribeDMUsers = nil
	mock.lockSubscribeDMUsers.Unlock()
}

// UnsubscribeDMUsers calls UnsubscribeDMUsersFunc.
func (mock *DMUsersProviderMock) UnsubscribeDMUsers(dMUserCh <-chan events.DMUser) {
	if mock.UnsubscribeDMUsersFunc == nil {
		panic("DMUsersProviderMock.UnsubscribeDMUsersFunc: method is nil but DMUsersProvider.UnsubscribeDMUsers was just called")
	}
	callInfo := struct {
		DMUserCh <-chan events.DMUser
	}{
		DMUserCh: dMUserCh,
	}
	mock.lockUnsubscribeDMUsers.Lock()
	mock.calls.UnsubscribeDMUsers = append(mock.calls.UnsubscribeDMUsers, callInfo)
	mock.lockUnsubscribeDMUsers.Unlock()
	mock.UnsubscribeDMUsersFunc(dMUserCh)
}

// UnsubscribeDMUsersCalls gets all the calls that were made to UnsubscribeDMUsers.
// Check the length with:
//
//	len(mockedDMUsersProvider.UnsubscribeDMUsersCalls())
func (mock *DMUsersProviderMock) UnsubscribeDMUsersCalls() []struct {
	DMUserCh <-chan events.DMUser
} {
	var calls []struct {
		DMUserCh <-chan events.DMUser
	}
	mock.lockUnsubscribeDMUsers.RLock()
	calls = mock.calls.UnsubscribeDMUsers
	mock.lockUnsubscribeDMUsers.RUnlock()
	return calls
}

// ResetUnsubscribeDMUsersCalls reset all the calls that were made to UnsubscribeDMUsers.
func (mock *DMUsersProviderMock) ResetUnsubscribeDMUsersCalls() {
	mock.lockUnsubscribeDMUsers.Lock()
	mock.calls.UnsubscribeDMUsers = nil
	mock.lockUnsubscribeDMUsers.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DMUsersProviderMock) ResetCalls() {
	mock.lockGetDMUsers.Lock()
	mock.calls.GetDMUsers = nil
	mock.lockGetDMUsers.Unlock()

	mock.lockSubscribeDMUsers.Lock()
	mock.calls.SubscribeDMUsers = nil
	mock.lockSubscribeDMUsers.Unlock()

	mock.lockUnsubscribeDMUsers.Lock()
	mock.calls.UnsubscribeDMUsers = nil
	mock.lockUnsubscribeDMUsers.Unlock()
}
